### ISSUE TITLE
Hide selected item when the user focuses the search input

### ISSUE THREAD

**Issue by amanharwara** [rob-balfre/svelte-select#187]
Right now, when a user focuses the search input, the selected item does not hide which makes it look like the user is editing the selected item even though it isn't so. This can become very confusing, which is why I suggest hiding the selected item text when the user focuses the search input.

**Comment by amanharwara** [comment]
This works:
```css
.selectContainer input ~ .selectedItem {
  visibility: hidden;
}
```
So you can close this if you want. But I think it's still worth implementing in main code itself.
