### ISSUE TITLE
[Feature] Placeholder opacity

### ISSUE THREAD

**Issue by CugeDe** [rob-balfre/svelte-select#189]
Hey there,

Thank you for this great package.

I would just ask for one small feature: a `--placeholderOpacity` var.

Many thanks.

**Comment by efreibe** [comment]
In the meantime you can set the opacity inside the style like:

```css
<style>
  :global(.selectContainer input::placeholder) {
     opacity: 0.5;
  }
</style>
```
