### ISSUE TITLE
CSS `padding` variable overruled?

### ISSUE THREAD

**Issue by blake-regalia** [rob-balfre/svelte-select#309]
https://github.com/rob-balfre/svelte-select/blob/442348f651fa1c0491a25d9eea5b51969651715e/src/Select.svelte#L681

This line overrides the `--padding` variable set in the root context and prevents me from controlling the amount of padding about the collapsed item.

**Comment by rob-balfre** [comment]
@blake-regalia yeah, that's not ideal at all.

You can override like so...

```css
:global(.selectContainer) {
    --padding: 20px !important;
}
```

Will keep open and fix up later.
