### ISSUE TITLE
Hover styles apply to first item by default

### ISSUE THREAD

**Issue by ZerdoX-x** [rob-balfre/svelte-select#378]
When I click on select with no value by default, dropdown appears and first item alrady has class "hover".

Workaround using global styles:
```css
/* unset fake "hover" styles */
:global(.selectContainer .item.hover:not(.active)) {
  background-color: transparent;
  color: var(--itemColor, inherit);
}
/* actual hover styles */
:global(.selectContainer .item.hover:hover) {
  background: var(--itemHoverBG, #e7f2ff);
  color: var(--itemHoverColor, inherit);
}
```
