### ISSUE TITLE
svelte-select@beta (v5) in a dialog. wrong list placement

### ISSUE THREAD

**Issue by ZerdoX-x** [rob-balfre/svelte-select#402]
To reproduce, add `@beta` or `@5.0.0-beta.11` to `svelte-select` import. Then try to open list.

https://svelte.dev/repl/f956c30152894d538a82a82725da4992?version=3.48.0

So I guess this is the code:
https://github.com/rob-balfre/svelte-select/blob/ce8f19683d07b8085755fb79bed2d6dfcf03c0e7/src/lib/List.svelte#L190-L217

**Comment by hmnd** [comment]
Experiencing this too when trying to use with carbon components.

**Comment by hmnd** [comment]
@ZerdoX-x I've found an interim fix that works for me with carbon. Just use the below CSS, and adjust the margins as needed:

```css
.svelte-select + .list {
	position: absolute !important;
	top: unset !important;
	margin-top: 0.5rem;
	margin-left: 1rem;
	left: 0 !important;
}
```
