### ISSUE TITLE
Outline input field when focused

### ISSUE THREAD

**Issue by DjeboDigital** [rob-balfre/svelte-select#519]
![image](https://user-images.githubusercontent.com/74966375/211842800-5e274dab-4873-442a-99ea-7b341208fc09.png)

More people have this issue? I tried to fix it with:

```css
input:focus {
     outline: none;
}
```

But this didn't do the trick.
