### ISSUE TITLE
Improve Tailwind implementation 

### ISSUE THREAD

**Issue by frederikhors** [rob-balfre/svelte-select#530]
I tried the code for https://github.com/rob-balfre/svelte-select/blob/master/src/lib/tailwind.css with v5.

It doesn't work (many issues).

Are you interested in keeping it or not?

If yes, I could find some time to investigate further.

**Comment by rob-balfre** [comment]
It's [experimental](https://github.com/rob-balfre/svelte-select#-experimental-replace-styles-tailwind-bootstrap-bulma-etc), more of a starting point for people really. I think others would love an improvement PR, thanks - I personally don't use TW and after trying it out wont be rushing back to it 😂.

**Comment by JVariance** [comment]
I used Tailwind's theme() function:
```css
	.svelte-select {
		--background: theme("backgroundColor.surface-container-high");
		--list-background: theme("backgroundColor.surface-container-high");
		--item-hover-bg: theme("backgroundColor.primary-fixed");
		--item-is-active-bg: theme("backgroundColor.primary-fixed");
		--item-active-background: theme("backgroundColor.primary-fixed");
		--item-is-active-color: theme("textColor.black");
		--multi-item-bg: theme("backgroundColor.primary-fixed");
	}
```
